schema_version = "1.0.0"

id = "dla_mountain_terrain"
version = "1.0.0"
name = "DLA Mountain Terrain"
tagline = "Generate fractal mountain ridges using DLA."
maintainer = "Michael Venous"
type = "add-on"

authors = [
    { name = "Michael", email = "the.michael.venous@gmail.com" }
]

maintainers = [
    { name = "Michael", email = "the.michael.venous@gmail.com" }
]

license = [
  "SPDX:GPL-3.0-or-later",
]

description = "Generate fractal mountain terrain using Diffusion‑Limited Aggregation (DLA) with real‑time blur and displacement controls."

tags = ["terrain", "generator", "DLA", "geometry nodes", "mountains"]

repository = "https://github.com/Michael-Venous/dla-mountain-ridge-addon.git"

blender_version_min = "4.2.0"
blender_version_max = "5.9.9"

pip = ["numba"]

module = "."
